id: firefox
title: Firefox
source: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
match:
  regex_process: Firefox
  regex_title: .*

hints:
  URL Navigation:
    Ctrl + L: Location bar
    Alt + Left: Back in History
    Alt + Right: Forward in History

  Tab Management:
    Ctrl + T: New tab
    Ctrl + Tab: Next tab
    Ctrl + 1..8: Select tab 1..8
    Ctrl + W: Close tab
    Ctrl + Shift + T: Undo close tab
    \/: Quick Find

  Various:
    Ctrl + Shift + Y: Show downloads
    Ctrl + g: Search in site
    Ctrl + G: Search next match

  Tridactyl - Modes:
    Esc: Normal
    f: Hint
    v: Visual
    ":": Command
    Shift + Esc: Ignore

  Tridactyl - Tabs:
    J / K: Next / previous
    d / x: Close
    u / X: Reopen
    t: Create new
    b: Switch between
    gt / GT: Go to next / previous
    yt: Duplicate
    W: Move tab new window

  Tridactyl - Normal:
    H / L: History back / forward
    o / O: Open URL in current tab
    t / T: Open URL in new tab
    w / W: Open URL in new Window
    p / P: Open clipboard in current/new tab
    s / S: Search with engine / in new tab
    gg / G: Scroll to start / end
    yy: Copy URL to clipboard
    zi / zo / zz: Zoom in / out / reset
    \/: Search

  Tridactyl - Hint:
    f: Open in current tab
    F: Open in new background tab
    ; + h: Select element
    ; + y: Copy link to clipboard
    ; + p: Copy element to clipboard
    ; + k: Kill element

  Tridactyl - Visual:
    hjklewb: Adjust selection
    "y": yank to clipboard
    s / S: Search selected text in current /new tab
    f: Open link in current tab
    F: Open link new current tab
    H: Back in History
    L: Forward in History
