id = "foot-terminal"
source = "https://codeberg.org/dnkl/foot#user-content-shortcuts"
include = ["cli"]

[match]
regex_process = "foot"
regex_title = ".*"

[section]
[section.Foot]
"Shift + PageUp / PageDown" = "Scroll up/down"
"Ctrl + Shift + c / v" = "Copy/paste from clipboard"
"Ctrl + Shift + r" = "Search mode"
"Ctrl + r / s" = "Search for previous / next match"
"Ctrl + Shift + u" = "URL mode"
t = "Toggle URL in label"
