id = "tilix"
url = "https://github.com/gnunn1/tilix/blob/master/data/resources/ui/shortcuts.ui"
include = ["cli"]

[match]
regex_wmclass = "tilix"
regex_title = ".*"

[section]
[section.Window]
F11 = "Toggle fullscreen"
F12 = "View session sidebar"

[section.Sessions]
"Ctrl + Shift + T" = "Open new session"
"Ctrl + PageUp / PageDown" = "Switch to next/preview session"
"Ctrl + Shift + Q" = "Close current session"

[section.Tiling]
"Ctrl + Alt + A" = "Add terminal automatically"
"Ctrl + Alt + R" = "Add terminal right"
"Ctrl + Alt + D" = "Add terminal down"
"Shift + Alt + Up Down Left Right" = "Resize terminal"
"Ctrl + Shift + W" = "Close"

[section.Terminal]
"Shift + Ctrl + F" = "Find"
"Shift + Ctrl + G / H" = "Find next / previous"
"Shift + Ctrl + Up Down" = "Scroll up / down"
"Shift + PageUp PageDown" = "Page up / down"
