id = "vim"
source = ""

[match]
regex_process = "(foot|kitty|gnome-terminal)"
regex_title = "^(n)?vim( .*)?$"

[section]
[section.Navigating]
"f / F + {c}" = "Jump to next / previous char"
"t / T + {c}" = "Move until next / previous char"
"; / ," = "Go to next / previous occurance"
"{ / }" = "Paragraph down / up"
"Ctrl + D / U\"" = "Half page down / up"
"gg / G" = "Jump to top/bottom of file"
gd = "Jump to definition"
gf = "Jump to file in import"
"%" = "Jump to matching bracket"

[section.Search]
"\\/ / ?" = "Search forward / backwards"
"n / N" = "Jump to next / previous match"
"* / #" = "Search next / previous word under cursor"

[section.Editing]
d = "Delete / whole line"
c = "Change (delete + insert)"
y = "Yank / whole line"
p = "Paste"
"Shift + i" = "Insert at beginning of line"
d5j = "Delete 5 lines downwards"
"df\"" = "Delete in line until \""
"dt\"" = "Delete in line until before \""
"d/foo" = "Delete from cursor util foo"
"> / <" = "Add / remove indentation"
"=" = "Format code"
"Ctrl + v & Up / Down" = "Visual block mode"
"Shift + i & # & Esc" = "Comment selected visual block"

[section.Registers]
"`\"+y`" = "yank to system clipboard"
"`\"+p`" = "paste from system clipboard"

[section.Syntax]
cc = "Double modify whole line"
D = "Capitalize for stronger/alt"
"{op} + a / i + {obj}" = "around / inner"
ciw = "Change inner word"
daw = "Delete a word"

[section."surround.vim"]
"ysiw)" = "Surround word under cursor with bracket"
"yss)" = "Surround whole line with bracket"
"cs)]" = "Change nearest brackets to squared brackets"
"ds)" = "Delete surrounding brackets"
