id = "vim"
url = ""

[match]
regex_wmclass = "(foot|kitty|gnome-terminal)"
regex_title = "^(n)?vim( .*)?$"

[section]

[section."Verbs (Operators)"]
"y / Y" = "Yank (copy) / until end"
"p / ]p" = "Paste / and adjust indent"
"d / D" = "Delete / until end"
"c / C" = "Change / until end"
"v / V" = "Visually select / whole line"
"> / <" = "Add / remove indentation"

[section.Modifiers]
i = "Inner"
a = "Around"
"{int}" = "x times"
"t / T + {c}" = "Toward next / previous char"
"f / F + {c}" = "Find next / previous char"
"/" = "Search"

[section."Nouns (Motions)"]
"Ctrl + d / u" = "Half page down / up"
"H / M / L" = "Top / middle / bottom of screen"
"0 / ^ / $" = "Line start / first non-blank / end"
"* / #" = "Next / previous token under cursor"
"b / B" = "Beginning of word / token"
"w / W" = "Next word / token"
"e / E" = "End of word / token"
"} / {" = "Next paragraph / previous paragraph"
"%" = "Jump to matching bracket"
"{mod} + p" = "Paragraph"
"{mod} + s" = "Sentence"
"{mod} + b" = "Block"
"{mod} + t" = "XML Tag"
"{mod} + \"" = "Quoted string"
"{mod} + ( / )" = "Paired brackets"

[section.Search]
"\\/ / ?" = "Search forward / backwards"
"n / N" = "Next / previous occurance"
"* / #" = "Search next / previous word under cursor"

[section.Navigating]
gd = "Go to definition"
gf = "Go to file in import"
"gg / G" = "Go to top/bottom of file"
5G = "Go to line 5"
"+" = "Go to first char of next line"
"ma / `a" = "Mark a / jump to a"

[section.Editing]
"i / I" = "Insert before cursor / line"
"a / A" = "Append after cursor / line"
"o / O" = "Open new line below / above"
"r / R" = "Replace char / and insert"
"s / S" = "Substitute char / line"
J = "Join lines"
"x / X" = "Exterminate char under / before cursor"
"u / Ctrl + r" = "Undo / redo"

[section."Useful commands"]
d5j = "Delete 5 lines downwards"
"df\"" = "Delete in line until \""
"dt\"" = "Delete in line until before \""
ea = "Append to end of word"
"d/foo" = "Delete from cursor until foo"
ciw = "Change inner word"
"gu / gU" = "Lowercase / uppercase"
"Ctrl + v & j / k" = "Visual block select"
"I & # & Esc" = "Comment selected visual block"
"\"ayi\"" = "Yank inner \" to register a"
"vi\"\"ap" = "Replace inner \" from register a"

[section.Registers]
"`\"ay`" = "yank to regesiter a"
"`\"ap`" = "paste from register a"
"`\"+y`" = "yank to system clipboard"
"`\"+p`" = "paste from system clipboard"
