title: VS Code
regex_process: code
regex_title: .*
hints:
  Navigating UI:
    Ctrl + 0: Focus sidebar
    Ctrl + 1: Focus editor 1
    Ctrl + 2: Focus editor 2
    Ctrl + b: Toggle sidebar
    Ctrl + j: Toggle panel
    Ctrl + Shift + e: Explorer in Sidebar
    Ctrl + Shift + m: Toggle problems
    Ctrl + `: Toggle terminal

  Basic Editing:
    Ctrl + l: Select current line
    Alt + Up/Down: Move line up/down
    Alt + Shift + Up/Down: Duplicate cursor
    Ctrl+ Alt + Shift + Up/Down: Duplicate line
    Shift + Alt + Left/Right: Expand/shrink selection
    Ctrl + h: Search and replace

  Language Editing:
    Ctrl + Space: Trigger IntelliSense and Hint
    Ctrl + Shift + o: Search and jump to symbol
    F12: Goto defintion
    Alt + F12: Peek definition
    Shift + F12: Peek usage
    F2: Rename symbol
    F8, Shift + F8: Cycle through errors

  Debugging:
    F9: Toogle breakpoint
    F5: Start/continue
    Shift + F5: Stop
    F11 / Shift + F11: Step into / out
    F10: Step over

  File/Tab Management:
    Ctrl + Tab: Switch between tabs
    Ctrl + p: Quick open file
