name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build AppImage on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.5
      - name: Install system deps
        run: |
          sudo apt-get update 
          sudo apt-get install \
             libgirepository1.0-dev \
             libcairo2-dev \
             python3-gi \
             gobject-introspection \
             libgtk-3-dev
      - name: Poetry install
        run: poetry install
      - name: Pytest
        run: poetry run pytest
      - name: Coveralls
        run: poetry run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      - name: Build and publish to PyPi-Test
        run: |
          poetry config repositories.pypi-test https://test.pypi.org/legacy/
          poetry publish \
            --build \
            --repository=pypi-test \
            --username __token__ \
            --password ${{ secrets.PYPI_TEST_KEYHINT_TOKEN }}
      - name: Build AppImage
        run: poetry run make clean-build

      # Release
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/*.AppImage
          body: See [CHANGELOG](https://github.com/dynobo/kehint/blob/master/CHANGELOG.md) for details.
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
