name: Build
on: [push, pull_request]

jobs:
  test_linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8          
      - uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.5
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install libgirepository1.0-dev libcairo2-dev python3-gi
      - name: Install appimagetool
        run: |
          mkdir linux
          wget https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x appimagetool
          mv appimagetool /home/runner/.local/bin/
      - name: Poetry install
        run: poetry install
      - name: Pytest
        run: poetry run pytest
      - name: Coveralls
        run: poetry run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      - name: Build AppImage
        run: poetry run make build
