name: "coverage.io"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install hatch
        run: pipx install hatch

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install \
             libgirepository1.0-dev \
             libcairo2-dev \
             python3-gi \
             gobject-introspection \
             libgtk-3-dev

      - name: Run pytest
        run: hatch run test

      - name: Coveralls
        run: hatch run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
