on: ["push"]

name: Coveralls

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # PREPARE
      - name: Install Python 3.7
        # Because GitHub Actions' python isn't build against tkinter!
        run: sudo apt-get update && sudo apt-get install python3.7 python3.7-dev python3.7-tk python3-setuptools
      - name: Symlink apt-pkg lib
        # to make pipenv working with different python versions
        run: cd /usr/lib/python3/dist-packages/ && sudo ln -s apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.so
      - name: Install normcap dependencies
        run: sudo apt-get install tesseract-ocr tesseract-ocr-deu libtesseract-dev libleptonica-dev pkg-config xclip
      - name: Install wheel
        run: python3.7 -m pip install --user wheel
      - name: Install pipenv
        run: python3.7 -m pip install --user pipenv
      - name: Create virtual env
        run: $HOME/.local/bin/pipenv install --dev
        env:
          CI: true

      - name: Install coveralls
        run: $HOME/.local/bin/pipenv run pip install coveralls

      # TEST
      - name: Test with pytest
        # xvfb-run with bpp 32 has to be used to make the mss screenshot grab work
        run: $HOME/.local/bin/pipenv run xvfb-run --server-args="-screen 0 1024x768x24+32" python3.7 -m pytest

      # PUBLISH
      - name: Publish
        run: $HOME/.local/bin/pipenv run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
