name: "coverage.io"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry==1.3.2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install \
             libgirepository1.0-dev \
             libcairo2-dev \
             python3-gi \
             gobject-introspection \
             libgtk-3-dev
      - name: Poetry install
        run: poetry install
      - name: Pytest
        run: poetry run pytest --cov --cov-report=xml
      - name: Coveralls
        run: poetry run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
