name: Publish
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
jobs:
  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.5
      - name: Install system deps
        run: |
          sudo apt-get update 
          sudo apt-get install \
             libgirepository1.0-dev \
             libcairo2-dev \
             python3-gi \
             gobject-introspection \
             libgtk-3-dev
      - name: Poetry install
        run: poetry install
      - name: Pytest
        run: poetry run pytest
      - name: Build and publish to PyPi
        run: |
          poetry publish \
            --build \
            --username __token__ \
            --password ${{ secrets.PYPI_KEYHINT_TOKEN }}
