name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test_linux:
    name: Test on Linux64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # PREPARE
      - name: Install Python 3.7
        # Because GitHub Actions' python isn't build against tkinter!
        run: sudo apt-get update && sudo apt-get install python3.7 python3.7-dev python3.7-tk python3-setuptools

      - name: Install dependencies
        run: python3.7 -m pip install -r requirements-dev.txt

      # LINT
      - name: Lint with pylama
        run: python3.7 -m pylama

      # TEST
      - name: Test with pytest
        run: xvfb-run --server-args="-screen 0 1024x768x24+32" python3.7 -m pytest

  # test_macos:
  #   name: Test on MacOS
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@master

  #     # PREPARE
  #     - name: Install normcap dependencies
  #       run: brew install pkg-config tesseract-lang
  #     - name: Install pipenv
  #       run: python3.7 -m pip install --user pipenv
  #     - name: Create virtual env
  #       run: $HOME/Library/Python/3.7/bin/pipenv install --dev
  #       env:
  #         CI: true

  #     # LINT
  #     - name: Lint with flake8
  #       run: $HOME/Library/Python/3.7/bin/pipenv run flake8 . --count --show-source --statistics

  #     # TEST
  #     - name: Test with pytest
  #       run: $HOME/Library/Python/3.7/bin/pipenv run python3.7 -m pytest

  test_windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      # PREPARE
      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt

      # LINT
      - name: Lint with flake8
        run: python -m pylama

      # TEST
      - name: Test with pytest
        run: python -m pytest
