name: Testss
on: [push, pull_request]

jobs:
  test_linux:
    name: Test on Linux64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.5
      - name: Poetry install
        run: poetry install
      - name: Pylint
        run: poetry run pylint

